name: Sprint5 Full Automation
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0
      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: ${{ secrets.AWS_REGION }}
      - name: Terraform Apply
        run: |
          cd sprint5-lab/infra
          terraform init
          terraform apply -auto-approve
      - name: Instalar Ansible
        run: |
          sudo apt-get update
          sudo amazon-linux-extras install ansible2 -y
          ansible --version
          pip3 install --user boto3

      - name: Configurar chave SSH para Ansible
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/lab7.pem
          chmod 600 ~/.ssh/lab7.pem
          ssh-keyscan -H 3.89.180.22 >> ~/.ssh/known_hosts
          
      - name: Configurar EC2 com Ansible
        run: |
          cd sprint5-lab/ansible
          ansible-playbook -i inventory setup.yml
      - name: Executar pipeline de dados
        run: |
          python sprint5-lab/scripts/data_pipeline.py
